name = "ur_control"
description = "Configuration file for the ur_control package."
author = "Georg John"
email = "georg.john@dfki.de"

[robot]
tool = "None"
connect_timeout = 5.0
home_radians = [3.014, -2.159, 2.258, -0.118, 1.362, -1.604]
ip_address = "192.168.11.40"  # Mobile robot with id 00040

[robot.joints]
vel = 0.35
max_vel = 0.5
acc = 0.1
max_acc = 0.5

[robot.tcp]
vel = 0.05
max_vel = 0.1
acc = 0.05
max_acc = 0.1

[robot.force_mode]
mode = 2
gain = 0.99
damping = 0.075
tcp_speed_limits = [0.025, 0.025, 0.025, 0.5, 0.5, 0.5]
