marker_size: 18
marker_type: 'DICT_4X4_100'
invert_img: true
marker_layout:
  71: [-22,  22]
  72: [51,   51]
  73: [51,  -51]
  74: [-51, -51]
offset:
  xyz: [0.0, 0.0, 0.0]
  xyzw: [0.0, 0.0, 0.0, 1.0]
