# Configuration file for state >>ArrangeJob<<

workspace_left:
  shoulder_pan_pos: 3.142
  home_joint_pos: [3.014, -2.159, 2.258, -0.118, 1.362, -1.604]

workspace_right:
  shoulder_pan_pos: 6.283
  home_joint_pos: [3.014, -2.159, 2.258, -0.118, 1.362, -1.604]
