# Configuration file for state >>MoveToPlugPreAttached<<

acc: 0.2

vel: 0.5

max_moving_tolerance: 1.6

marker:
  type2_male: aruco_marker_type2_male
  ccs_female: aruco_marker_ccs_female
  type2_female: aruco_marker_type2_female

plug_in_ads_ac:
  trans_base2socket: [0.5726, 0.2223, 0.2170]  # [0.5714, 0.2215, 0.2183]
  eulvec_base2socket: [0.0335, 2.0917, 0.0116]  # [0.0405, 2.0756, 0.0196]
