plug_out_ads_ac:
  two_step_approach: true
  detector_cfg:
    - aruco_marker_ads_ac_adj.yaml
    - aruco_pattern_ads_ac_adj.yaml

plug_out_ads_dc:
  two_step_approach: true
  detector_cfg:
    - aruco_marker_ads_ac_adj.yaml
    - aruco_pattern_ads_ac_adj.yaml

plug_out_bcs_ac:
  two_step_approach: true
  detector_cfg:
    - aruco_marker_ads_ac_adj.yaml
    - aruco_pattern_ads_ac_adj.yaml
