# Configuration file for state >>ObservePlug<<

acc: 0.2

vel: 0.5

plug_out_ads_ac:
  two_step_approach: true
  time_out: 5.0
  detector_i: aruco_marker_ads
  detector_ii: aruco_pattern_ads_adj

plug_out_ads_dc:
  two_step_approach: true
  time_out: 5.0
  detector_i: aruco_marker_ads
  detector_ii: aruco_pattern_ads_adj

plug_out_bcs_ac:
  two_step_approach: true
  time_out: 5.0
  detector_i: aruco_marker_ads
  detector_ii: aruco_pattern_ads_adj